/**
 * Starter projects generated by `clever init`: the smallest application that deploys and answers on Clever Cloud.
 */

/**
 * @typedef {object} StarterTemplate
 * @property {string} description
 * @property {(name: string) => Record<string, string>} files relative path → content
 * @property {Record<string, string>} env environment variables set on the application at creation
 * @property {string} runLocally command to start the application on the developer machine
 */

const HTTP_PORT = 8080;

/**
 * @param {string} name
 * @param {string} runtime
 * @returns {string}
 */
function welcomePage(name, runtime) {
  name = escapeHtml(name);
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>${name}</title>
  </head>
  <body style="font-family: system-ui, sans-serif; max-width: 40rem; margin: 4rem auto; padding: 0 1rem">
    <h1>${name}</h1>
    <p>Your ${runtime} application is running on Clever Cloud.</p>
  </body>
</html>
`;
}

/**
 * @param {string} name
 * @param {string} runtime
 * @returns {string}
 */
function nodeServer(name, runtime) {
  return `const http = require('node:http');

const port = Number(process.env.PORT ?? ${HTTP_PORT});

const page = \`${welcomePage(name, runtime)}\`;

const server = http.createServer((request, response) => {
  if (request.url === '/health') {
    response.writeHead(200, { 'content-type': 'text/plain' });
    response.end('ok');
    return;
  }
  response.writeHead(200, { 'content-type': 'text/html; charset=utf-8' });
  response.end(page);
});

server.listen(port, '0.0.0.0', () => {
  console.log(\`Listening on port \${port}\`);
});
`;
}

/**
 * @param {string} name
 * @param {string} runLocally
 * @param {string[]} [notes]
 * @returns {string}
 */
function readme(name, runLocally, notes = []) {
  return [
    `# ${name}`,
    '',
    'Generated by `clever init`.',
    '',
    '## Run locally',
    '',
    '```bash',
    runLocally,
    '```',
    '',
    `Then open http://localhost:${HTTP_PORT}`,
    '',
    '## Deploy on Clever Cloud',
    '',
    '```bash',
    'git add . && git commit -m "My changes"',
    'clever deploy',
    'clever open',
    '```',
    ...(notes.length > 0 ? ['', '## Notes', '', ...notes.map((note) => `- ${note}`)] : []),
    '',
  ].join('\n');
}

/** @type {Record<string, StarterTemplate>} */
export const STARTER_TEMPLATES = {
  docker: {
    description: 'Dockerfile running a small Node.js HTTP server',
    env: {},
    runLocally: `docker build -t app . && docker run --rm -p ${HTTP_PORT}:${HTTP_PORT} app`,
    files(name) {
      return {
        Dockerfile: [
          'FROM node:24-alpine',
          'WORKDIR /app',
          'COPY server.js .',
          `ENV PORT=${HTTP_PORT}`,
          `EXPOSE ${HTTP_PORT}`,
          'USER node',
          'CMD ["node", "server.js"]',
          '',
        ].join('\n'),
        '.dockerignore': ['.git', '.clever.json', '*.md', ''].join('\n'),
        'server.js': nodeServer(name, 'Docker'),
        '.gitignore': ['.env', ''].join('\n'),
        'README.md': readme(name, this.runLocally, [
          `Clever Cloud sends HTTP traffic to port ${HTTP_PORT}: keep the server listening on it.`,
          'Replace the image and server.js with your own stack, the Dockerfile is all Clever Cloud needs.',
        ]),
      };
    },
  },
  node: {
    description: 'Node.js HTTP server without dependencies',
    env: {},
    runLocally: 'npm start',
    files(name) {
      return {
        'package.json': `${JSON.stringify(
          {
            name: toPackageName(name),
            version: '1.0.0',
            private: true,
            scripts: { start: 'node server.js' },
            engines: { node: '>=24' },
          },
          null,
          2,
        )}\n`,
        'server.js': nodeServer(name, 'Node.js'),
        '.gitignore': ['node_modules/', '.env', ''].join('\n'),
        'README.md': readme(name, this.runLocally, [
          'Clever Cloud runs `npm start` and provides the port in the PORT environment variable.',
          'The Node.js version is chosen from `engines.node` in package.json.',
        ]),
      };
    },
  },
  python: {
    description: 'Flask application served by Clever Cloud (CC_PYTHON_MODULE)',
    env: { CC_PYTHON_MODULE: 'app:app' },
    runLocally: 'python3 -m venv .venv && .venv/bin/pip install -r requirements.txt && .venv/bin/python app.py',
    files(name) {
      return {
        'app.py': `import os

from flask import Flask

app = Flask(__name__)

PAGE = """${welcomePage(name, 'Python')}"""


@app.get("/")
def index():
    return PAGE


@app.get("/health")
def health():
    return "ok"


if __name__ == "__main__":
    # Local development only: on Clever Cloud the app object is served through CC_PYTHON_MODULE
    app.run(host="0.0.0.0", port=int(os.environ.get("PORT", ${HTTP_PORT})))
`,
        'requirements.txt': ['Flask>=3.1,<4', ''].join('\n'),
        '.gitignore': ['.venv/', '__pycache__/', '.env', ''].join('\n'),
        'README.md': readme(name, this.runLocally, [
          'On Clever Cloud the `app` object of app.py is served thanks to `CC_PYTHON_MODULE=app:app` (set by `clever init`).',
          'Dependencies are installed from requirements.txt at each deployment.',
        ]),
      };
    },
  },
  php: {
    description: 'PHP page served by Apache',
    env: {},
    runLocally: `php -S 0.0.0.0:${HTTP_PORT}`,
    files(name) {
      return {
        'index.php': `<?php

// Every request without a matching file reaches this front controller (.htaccess on Apache)
$path = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH);

if ($path === '/health') {
    header('Content-Type: text/plain');
    echo 'ok';
    return;
}
?>
${welcomePage(name, 'PHP').replace('.</p>', ' with PHP <?= htmlspecialchars(PHP_VERSION) ?>.</p>')}`,
        '.htaccess': [
          'RewriteEngine On',
          'RewriteCond %{REQUEST_FILENAME} !-f',
          'RewriteCond %{REQUEST_FILENAME} !-d',
          'RewriteRule ^ index.php [QSA,L]',
          '',
        ].join('\n'),
        '.gitignore': ['vendor/', '.env', ''].join('\n'),
        'README.md': readme(name, this.runLocally, [
          'Apache serves the root of the repository. Move the public files to a folder and `clever env set CC_WEBROOT /public` if needed.',
          'Requests that match no file are routed to index.php by .htaccess.',
          'Add a composer.json to install dependencies at each deployment.',
        ]),
      };
    },
  },
  go: {
    description: 'Go HTTP server using only the standard library',
    env: {},
    runLocally: 'go run .',
    files(name) {
      return {
        'go.mod': [`module ${toPackageName(name)}`, '', 'go 1.23', ''].join('\n'),
        'main.go': `package main

import (
\t"log"
\t"net/http"
\t"os"
)

const page = \`${welcomePage(name, 'Go')}\`

func main() {
\tport := os.Getenv("PORT")
\tif port == "" {
\t\tport = "${HTTP_PORT}"
\t}

\thttp.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
\t\tw.Header().Set("Content-Type", "text/plain")
\t\tw.Write([]byte("ok"))
\t})
\thttp.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
\t\tw.Header().Set("Content-Type", "text/html; charset=utf-8")
\t\tw.Write([]byte(page))
\t})

\tlog.Printf("Listening on port %s", port)
\tlog.Fatal(http.ListenAndServe("0.0.0.0:"+port, nil))
}
`,
        '.gitignore': [`/${toPackageName(name)}`, '.env', ''].join('\n'),
        'README.md': readme(name, this.runLocally, [
          'Clever Cloud builds the main package at the root of the module and provides the port in the PORT environment variable.',
          'The Go version is read from go.mod.',
        ]),
      };
    },
  },
  static: {
    description: 'Static website served as is',
    env: {},
    runLocally: `python3 -m http.server ${HTTP_PORT}`,
    files(name) {
      return {
        'index.html': welcomePage(name, 'static'),
        'health.txt': 'ok\n',
        '.gitignore': ['.env', ''].join('\n'),
        'README.md': readme(name, this.runLocally, [
          'Every file of the repository is served as is: add your HTML, CSS, JS and images next to index.html.',
          'To serve a build output instead (dist/, build/, public/...), `clever env set CC_WEBROOT /dist`.',
        ]),
      };
    },
  },
};

/**
 * Escape a value for HTML, also safe inside the JS template literal and Python string embedding the page
 * @param {string} value
 * @returns {string}
 */
function escapeHtml(value) {
  return value.replace(/[&<>"'`$\\]/g, (character) => `&#${character.charCodeAt(0)};`);
}

/**
 * @param {string} name
 * @returns {string}
 */
function toPackageName(name) {
  const packageName = name
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^[._-]+|-+$/g, '');
  return packageName === '' ? 'app' : packageName;
}

/**
 * @returns {string[]}
 */
export function listStarterRuntimes() {
  return Object.keys(STARTER_TEMPLATES);
}
