import { planCodeFixes } from './code-fixes.js';
import { shellQuote } from './report.js';
import { isRewiringAutomatic } from './rewiring.js';
import { findHardcodedPhpConnections, isLocalHost } from './rules/database.js';

/**
 * @typedef {import('./project-scanner.js').ProjectScanner} ProjectScanner
 * @typedef {import('./report.js').MigrationReport} MigrationReport
 * @typedef {import('./report.js').Finding} Finding
 */

/**
 * @typedef {object} PlannedChange
 * @property {string} path relative to the project root
 * @property {string} content full content to write
 * @property {'create'|'update'} action
 * @property {string} description
 * @property {'config'|'code'|'setup'|'secrets'} group commits are grouped by kind, secrets are never committed
 * @property {boolean} [executable]
 */

export const GENERATED_MARKER = 'Generated by `clever migrate apply`';
export const ENV_FILE = '.env.clever';
export const SETUP_SCRIPT = 'clever-setup.sh';
export const MIGRATION_GUIDE = 'CLEVER-MIGRATION.md';
export const DATA_SCRIPT = 'clever-migrate-data.sh';

/** Findings fully handled by the generated files and setup script */
const HANDLED_FINDINGS = new Set([
  'docker.dockerfile-location',
  'docker.http-port',
  'docker.dockerignore',
  'compose.not-supported',
  'compose.service-to-addon',
  'database.addon',
  'compose.worker',
  'compose.docker-socket',
  'node.build-step',
  'node.dev-dependencies',
  'php.webroot',
  'python.entrypoint',
  'python.alembic',
  'go.main-package',
  'rust.multiple-bins',
  'static.build',
  'platform.procfile',
  'env.dotenv',
  'env.dotenv-committed',
  'cron.crontab',
]);

const DOCKERIGNORE_ENTRIES = {
  common: ['.git', '.env', '.env.*', '!.env.example', 'clever-setup.sh', 'CLEVER-MIGRATION.md', '.clever.json'],
  node: ['node_modules', 'npm-debug.log*', 'coverage', '.next/cache'],
  python: ['.venv', 'venv', '__pycache__', '*.pyc', '.pytest_cache', '.ruff_cache', '.mypy_cache'],
  php: ['vendor', 'var/cache', 'var/log'],
  go: ['bin'],
  rust: ['target'],
  java: ['target', 'build', '.gradle'],
};

/** Findings that code fixes can solve, matched by location */
const CODE_FINDINGS = new Set([
  'code.hardcoded-port',
  'code.loopback-binding',
  'node.next-port',
  'java.port',
  'database.hardcoded-credentials',
]);

/**
 * Compute every file `clever migrate apply` would create or update
 * @param {ProjectScanner} scanner
 * @param {MigrationReport} report
 * @param {{ code?: boolean }} [options] code: also rewrite source files for well known patterns
 * @returns {{ changes: PlannedChange[], todo: Finding[], done: Finding[], edits: import('./code-fixes.js').CodeEdit[] }}
 */
export function planMigrationFiles(scanner, report, { code = true } = {}) {
  /** @type {PlannedChange[]} */
  const changes = [];

  const {
    changes: codeChanges,
    edits,
    manual: codeManualSteps,
  } = code ? planCodeFixes(scanner, report) : { changes: [], edits: [], manual: [] };
  changes.push(...codeChanges);
  const editedLocations = new Set(edits.flatMap((edit) => [`${edit.file}:${edit.line}`, edit.file]));
  const isFixedByCode = (/** @type {Finding} */ finding) =>
    CODE_FINDINGS.has(finding.id) && finding.location != null && editedLocations.has(finding.location);

  for (const file of report.files) {
    if (!scanner.has(file.path)) {
      changes.push({
        path: file.path,
        content: file.content,
        action: 'create',
        description: file.reason,
        group: 'config',
      });
    }
  }

  if (report.runtime.type === 'docker' && !scanner.has('.dockerignore')) {
    changes.push({
      path: '.dockerignore',
      content: buildDockerignore(scanner),
      action: 'create',
      description: 'Keeps secrets, git history and local dependencies out of the Docker build',
      group: 'config',
    });
  }

  const envClever = buildEnvClever(scanner, report);
  const gitignoreChange = buildGitignore(scanner, envClever != null);
  if (gitignoreChange != null) {
    changes.push(gitignoreChange);
  }
  if (envClever != null) {
    changes.push({
      path: ENV_FILE,
      content: envClever.content,
      action: scanner.has(ENV_FILE) ? 'update' : 'create',
      description: 'Production environment variables, imported by the setup script',
      group: 'secrets',
    });
  }

  changes.push({
    path: SETUP_SCRIPT,
    content: buildSetupScript(report, envClever != null),
    action: scanner.has(SETUP_SCRIPT) ? 'update' : 'create',
    description: 'Creates the application, add-ons and environment variables on Clever Cloud',
    group: 'setup',
    executable: true,
  });

  const dataScript = buildDataScript(scanner, report);
  if (dataScript != null) {
    changes.push({
      path: DATA_SCRIPT,
      content: dataScript,
      action: scanner.has(DATA_SCRIPT) ? 'update' : 'create',
      description: 'Copies the local databases into the add-ons (run it after the setup script)',
      group: 'setup',
      executable: true,
    });
  }

  const done = report.findings.filter((finding) => isHandled(finding, report) || isFixedByCode(finding));
  const todo = report.findings.filter(
    (finding) => finding.severity !== 'info' && !isHandled(finding, report) && !isFixedByCode(finding),
  );
  todo.push(...codeManualSteps, ...(envClever?.manualSteps ?? []));

  changes.push({
    path: MIGRATION_GUIDE,
    content: buildMigrationGuide(report, changes, done, todo, edits),
    action: scanner.has(MIGRATION_GUIDE) ? 'update' : 'create',
    description: 'What was done and what remains to do',
    group: 'setup',
  });

  return { changes, todo, done, edits };
}

/**
 * @param {Finding} finding
 * @param {MigrationReport} report
 * @returns {boolean}
 */
function isHandled(finding, report) {
  if (finding.id === 'compose.service-hostnames') {
    // Only when every variable can be rebuilt from an add-on variable
    return report.rewired.filter((variable) => variable.service !== 'local database').every(isRewiringAutomatic);
  }
  if (finding.id === 'database.env-rewired') {
    return report.rewired.filter((variable) => variable.service === 'local database').every(isRewiringAutomatic);
  }
  if (finding.id === 'env.dev-values') {
    return report.devValues.every((devValue) => devValue.kind === 'mode');
  }
  return HANDLED_FINDINGS.has(finding.id);
}

/**
 * @param {ProjectScanner} scanner
 * @returns {string}
 */
function buildDockerignore(scanner) {
  const entries = [...DOCKERIGNORE_ENTRIES.common];
  if (scanner.has('package.json')) {
    entries.push(...DOCKERIGNORE_ENTRIES.node);
  }
  if (scanner.first(['requirements.txt', 'pyproject.toml', 'Pipfile']) != null) {
    entries.push(...DOCKERIGNORE_ENTRIES.python);
  }
  if (scanner.has('composer.json')) {
    entries.push(...DOCKERIGNORE_ENTRIES.php);
  }
  if (scanner.has('go.mod')) {
    entries.push(...DOCKERIGNORE_ENTRIES.go);
  }
  if (scanner.has('Cargo.toml')) {
    entries.push(...DOCKERIGNORE_ENTRIES.rust);
  }
  if (scanner.first(['pom.xml', 'build.gradle', 'build.gradle.kts']) != null) {
    entries.push(...DOCKERIGNORE_ENTRIES.java);
  }
  return `# ${GENERATED_MARKER}\n${[...new Set(entries)].join('\n')}\n`;
}

/**
 * Make sure local secrets are never pushed with `clever deploy`
 * @param {ProjectScanner} scanner
 * @param {boolean} hasEnvClever
 * @returns {PlannedChange|null}
 */
function buildGitignore(scanner, hasEnvClever) {
  const current = scanner.read('.gitignore') ?? '';
  const lines = current.split(/\r?\n/).map((line) => line.trim());
  const isIgnored = (/** @type {string} */ file) =>
    lines.some(
      (line) =>
        line === file ||
        line === `/${file}` ||
        (line.endsWith('*') && file.startsWith(line.slice(0, -1).replace(/^\//, ''))),
    );

  const missing = [];
  if (scanner.has('.env') && !isIgnored('.env')) {
    missing.push('.env');
  }
  if (hasEnvClever && !isIgnored(ENV_FILE)) {
    missing.push(ENV_FILE);
  }
  if (missing.length === 0) {
    return null;
  }
  const separator = current === '' || current.endsWith('\n') ? '' : '\n';
  return {
    path: '.gitignore',
    content: `${current}${separator}${current === '' ? '' : '\n'}# Local secrets (clever migrate)\n${missing.join('\n')}\n`,
    action: scanner.has('.gitignore') ? 'update' : 'create',
    description: `Ignore ${missing.join(', ')}`,
    group: 'config',
  };
}

/**
 * Production .env built from the local ones: service hostnames removed, dev values fixed, missing variables listed
 * @param {ProjectScanner} scanner
 * @param {MigrationReport} report
 * @returns {{ content: string, manualSteps: Finding[] }|null}
 */
function buildEnvClever(scanner, report) {
  /** @type {Map<string, { value: string, file: string }>} */
  const variables = new Map();
  for (const file of report.envFilesToImport) {
    for (const [name, value] of Object.entries(scanner.readEnvFile(file) ?? {})) {
      variables.set(name, { value, file });
    }
  }
  const exampleFile = scanner.first(['.env.example', '.env.dist', '.env.sample', '.env.template']);
  const expected = Object.keys(exampleFile != null ? (scanner.readEnvFile(exampleFile) ?? {}) : {});
  if (variables.size === 0 && expected.length === 0) {
    return null;
  }

  const lines = [
    `# ${GENERATED_MARKER} from ${[...report.envFilesToImport, exampleFile].filter(Boolean).join(', ')}`,
    '# Production environment of the application. It contains secrets: never commit it.',
    `# ${SETUP_SCRIPT} imports it with \`clever env import\`, which REPLACES all the variables of the application.`,
    '# Format: NAME=value, one per line, no inline comment.',
    '',
  ];
  /** @type {Finding[]} */
  const manualSteps = [];

  for (const [name, { value, file }] of variables) {
    if (report.env[name] != null) {
      lines.push(`# ${name} is set by ${SETUP_SCRIPT}: ${report.env[name].reason}`);
      continue;
    }
    const rewired = report.rewired.find((variable) => variable.name === name);
    if (rewired != null) {
      if (rewired.addonVariable === name) {
        lines.push(`# ${name} is injected by the ${rewired.addonName ?? rewired.service} add-on`);
      } else if (isRewiringAutomatic(rewired)) {
        const from = rewired.addonVariable ?? Object.values(rewired.uriParts ?? {}).join(', ');
        lines.push(`# ${name} is computed by ${SETUP_SCRIPT} from ${from}`);
      } else {
        lines.push(
          `# TODO ${name} pointed to the ${rewired.service === 'local database' ? 'local database' : `"${rewired.service}" service`}, set its production value`,
          `# ${name}=`,
        );
        manualSteps.push({
          id: 'apply.rewire-manually',
          severity: 'warning',
          title: `Set ${name} in ${ENV_FILE}: it pointed to the "${rewired.service}" docker-compose service`,
          location: ENV_FILE,
        });
      }
      continue;
    }
    const devValue = report.devValues.find((candidate) => candidate.name === name && candidate.file === file);
    if (devValue?.kind === 'mode') {
      lines.push(`# ${name} was "${value}" in ${file}`, `${name}=${productionMode(name, report)}`);
      continue;
    }
    if (devValue?.kind === 'url') {
      lines.push(
        `# TODO ${name} was ${value}: set the public URL (https://<app>.cleverapps.io or your domain)`,
        `# ${name}=`,
      );
      manualSteps.push({
        id: 'apply.public-url',
        severity: 'warning',
        title: `Set ${name} to the public URL of the application in ${ENV_FILE}`,
        location: ENV_FILE,
      });
      continue;
    }
    lines.push(`${name}=${formatEnvValue(value)}`);
  }

  const missing = expected.filter(
    (name) =>
      !variables.has(name) && report.env[name] == null && !report.rewired.some((variable) => variable.name === name),
  );
  if (missing.length > 0) {
    lines.push('', `# TODO Variables expected by ${exampleFile} but not defined locally, uncomment and fill them:`);
    const exampleValues = exampleFile != null ? (scanner.readEnvFile(exampleFile) ?? {}) : {};
    lines.push(...missing.map((name) => `# ${name}=${exampleValues[name] ?? ''}`));
    manualSteps.push({
      id: 'apply.missing-variables',
      severity: 'warning',
      title: `Fill the variables expected by ${exampleFile} in ${ENV_FILE}: ${missing.join(', ')}`,
      location: ENV_FILE,
    });
  }

  return { content: lines.join('\n') + '\n', manualSteps };
}

/**
 * @param {string} name
 * @param {MigrationReport} report
 * @returns {string}
 */
function productionMode(name, report) {
  if (name === 'APP_ENV' && report.env.APP_ENV != null) {
    return report.env.APP_ENV.value;
  }
  if (name === 'MIX_ENV') {
    return 'prod';
  }
  return 'production';
}

/**
 * Quote values the way `clever env import` expects them
 * @param {string} value
 * @returns {string}
 */
function formatEnvValue(value) {
  if (/^[^\s'"#\\]*$/.test(value)) {
    return value;
  }
  return `"${value.replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`;
}

/**
 * @param {MigrationReport} report
 * @param {boolean} hasEnvClever
 * @returns {string}
 */
function buildSetupScript(report, hasEnvClever) {
  const app = report.appName;
  const lines = [
    '#!/usr/bin/env bash',
    `# ${GENERATED_MARKER}.`,
    '# Creates the Clever Cloud application, its add-ons and its environment variables.',
    '# Review it before running it, once, from a logged-in terminal (`clever login`).',
    '# Add-ons may not be free: `clever addon create` asks for confirmation when needed.',
    'set -euo pipefail',
    'cd "$(dirname "$0")"',
    '',
    `APP=${shellQuote(report.linkedApp ?? app)}`,
    '',
  ];

  if (report.rewired.some(isRewiringAutomatic)) {
    lines.push(...ADDON_VAR_FUNCTION, '');
  }

  if (report.runtime.type == null) {
    lines.push('echo "No runtime detected: run \\`clever migrate --type <type>\\` first" >&2', 'exit 1', '');
    return lines.join('\n');
  }

  // The script can be run again: existing application and add-ons are reused
  lines.push(
    ...EXISTENCE_FUNCTIONS,
    '',
    'echo "→ Application"',
    'if app_linked "$APP"; then',
    '  echo "  $APP is already linked (.clever.json), reusing it"',
    'else',
    `  clever create --type ${report.runtime.type} "$APP"`,
    'fi',
    '',
  );

  if (report.addons.length > 0) {
    lines.push('echo "→ Add-ons"');
    for (const addon of report.addons) {
      const origin = addon.fromService != null ? ` (replaces the "${addon.fromService}" service)` : '';
      const name = shellQuote(addon.name);
      lines.push(
        `# ${addon.label}${origin}`,
        `if addon_exists ${name}; then`,
        `  echo "  ${addon.name} already exists, linking it"`,
        `  clever service link-addon ${name} --alias "$APP" >/dev/null 2>&1 || true`,
        'else',
        `  clever addon create ${addon.provider} ${name} --link "$APP"`,
        'fi',
      );
    }
    lines.push('');
  }

  lines.push('echo "→ Environment variables"');
  if (hasEnvClever) {
    lines.push(`# Must run first: it replaces all the variables of the application`, `clever env import < ${ENV_FILE}`);
  }
  for (const [name, { value, reason }] of Object.entries(report.env)) {
    lines.push(`# ${reason}`, `clever env set ${name} ${shellQuote(value)}`);
  }
  for (const variable of report.rewired) {
    if (!isRewiringAutomatic(variable) || variable.addonVariable === variable.name) {
      continue;
    }
    lines.push(
      `# ${variable.name} pointed to the ${variable.service === 'local database' ? 'local database' : `"${variable.service}" service`}`,
    );
    lines.push(...setRewiredVariable(variable));
  }
  lines.push('');

  for (const extraApp of report.extraApps) {
    lines.push(`echo "→ Application ${extraApp.name}"`, `# ${extraApp.reason}`);
    lines.push(
      `clever create --type ${extraApp.type} ${shellQuote(extraApp.name)} --alias ${shellQuote(extraApp.name)}`,
    );
    for (const [name, value] of Object.entries(extraApp.env)) {
      lines.push(`clever env set ${name} ${shellQuote(value)} --alias ${shellQuote(extraApp.name)}`);
    }
    if (extraApp.linkAddons) {
      for (const addon of report.addons) {
        lines.push(`clever service link-addon ${shellQuote(addon.name)} --alias ${shellQuote(extraApp.name)}`);
      }
    }
    lines.push('');
  }

  lines.push(
    'echo',
    `echo "Done. Check ${MIGRATION_GUIDE} for the remaining manual steps, then deploy:"`,
    'echo "  git add . && git commit -m \\"Prepare deployment on Clever Cloud\\""',
    'echo "  clever deploy"',
    '',
  );
  return lines.join('\n');
}

/**
 * @param {MigrationReport} report
 * @param {PlannedChange[]} changes
 * @param {Finding[]} done
 * @param {Finding[]} todo
 * @param {import('./code-fixes.js').CodeEdit[]} edits
 * @returns {string}
 */
function buildMigrationGuide(report, changes, done, todo, edits) {
  const lines = [
    '# Migration to Clever Cloud',
    '',
    `> ${GENERATED_MARKER}. Readiness before migration: **${report.score}/100**.`,
    '',
    `- **Application**: \`${report.appName}\``,
    `- **Runtime**: \`${report.runtime.type ?? 'unknown'}\` (${report.runtime.reason})`,
  ];
  if (report.addons.length > 0) {
    lines.push(`- **Add-ons**: ${report.addons.map((addon) => `${addon.label} (\`${addon.name}\`)`).join(', ')}`);
  }

  lines.push('', '## Steps', '');
  let step = 1;
  if (changes.some((change) => change.path === ENV_FILE)) {
    lines.push(
      `${step++}. Review \`${ENV_FILE}\` and fill the \`TODO\` lines (this file holds secrets and is not committed)`,
    );
  }
  if (todo.length > 0) {
    lines.push(`${step++}. Do the manual changes listed below`);
  }
  lines.push(
    `${step++}. Review and run \`./${SETUP_SCRIPT}\` (once, after \`clever login\`)`,
    ...(changes.some((change) => change.path === DATA_SCRIPT)
      ? [`${step++}. Copy your data with \`./${DATA_SCRIPT}\` (the add-ons start empty)`]
      : []),
    `${step++}. Commit and deploy: \`git add . && git commit -m "Prepare deployment on Clever Cloud" && clever deploy\``,
    `${step++}. Follow the deployment with \`clever logs\`, then open it with \`clever open\``,
  );

  lines.push('', '## Files generated', '');
  for (const change of changes) {
    lines.push(`- \`${change.path}\` (${change.action === 'create' ? 'created' : 'updated'}): ${change.description}`);
  }
  lines.push(`- \`${MIGRATION_GUIDE}\`: this guide`);

  if (edits.length > 0) {
    lines.push(
      '',
      '## Code changes',
      '',
      'The original values stay the default when the variable is not defined, so local development is unchanged.',
      '',
    );
    for (const edit of edits) {
      lines.push(
        `- \`${edit.file}:${edit.line}\`: ${edit.reason}`,
        '',
        '  ```diff',
        ...(edit.before !== '' ? [`  - ${edit.before}`] : []),
        `  + ${edit.after}`,
        '  ```',
        '',
      );
    }
  }

  if (todo.length > 0) {
    lines.push('', '## To do manually', '');
    for (const finding of todo) {
      lines.push(...formatFinding(finding, '- [ ]'));
    }
  }

  if (done.length > 0) {
    lines.push('', '## Handled by the generated files', '');
    for (const finding of done) {
      lines.push(`- [x] ${stripBackquotes(finding.title)}`);
    }
  }

  lines.push(
    '',
    '---',
    '',
    'The analysis is static: double check the plan, and run `clever migrate` again after your changes.',
    '',
  );
  return lines.join('\n');
}

/**
 * @param {Finding} finding
 * @param {string} prefix
 * @returns {string[]}
 */
function formatFinding(finding, prefix) {
  const severity = finding.severity === 'blocker' ? '**Blocker**' : 'Warning';
  const lines = [
    `${prefix} ${severity}: ${stripBackquotes(finding.title)}${finding.location != null ? ` (\`${finding.location}\`)` : ''}`,
  ];
  if (finding.details != null) {
    lines.push(...finding.details.split('\n').map((line) => `  - ${line}`));
  }
  for (const fix of finding.fix ?? []) {
    lines.push(`  - → ${fix}`);
  }
  return lines;
}

/**
 * Titles may contain backquotes meant for the terminal, they are fine in Markdown too but unbalanced ones are not
 * @param {string} text
 * @returns {string}
 */
function stripBackquotes(text) {
  return (text.match(/`/g) ?? []).length % 2 === 0 ? text : text.replaceAll('`', '');
}

/** Bash function printing a variable exposed by an add-on: addon_var <add-on name> <variable> */
const ADDON_VAR_FUNCTION = [
  '# Print a variable exposed by an add-on: addon_var <add-on name> <variable>',
  'addon_var() {',
  '  local addon_id value',
  `  addon_id=$(clever addon list --format json | node -e 'const addons = JSON.parse(require("fs").readFileSync(0, "utf8")); const addon = addons.find((a) => a.name === process.argv[1]); if (addon == null) process.exit(1); process.stdout.write(addon.addonId)' "$1")`,
  `  value=$(clever addon env "$addon_id" --format json | node -e 'const env = JSON.parse(require("fs").readFileSync(0, "utf8")); process.stdout.write(env[process.argv[1]] ?? "")' "$2")`,
  '  [ -n "$value" ] || { echo "$2 not found on add-on $1" >&2; exit 1; }',
  '  printf %s "$value"',
  '}',
];

/**
 * Bash lines computing a variable from add-on variables and setting it on the application
 * @param {import('./report.js').RewiredVariable} variable
 * @returns {string[]}
 */
function setRewiredVariable(variable) {
  const addonName = shellQuote(variable.addonName ?? '');
  const prefix = variable.name.replace(/[^A-Z0-9_]/gi, '_');
  const query = escapeDoubleQuoted(variable.query ?? '');
  if (variable.uriParts != null) {
    const parts = /** @type {Record<string, string>} */ (variable.uriParts);
    const lines = Object.entries(parts).map(
      ([role, addonVariable]) => `${prefix}_${role.toUpperCase()}="$(addon_var ${addonName} ${addonVariable})"`,
    );
    const uri = `${variable.scheme}://\${${prefix}_USER}:\${${prefix}_PASSWORD}@\${${prefix}_HOST}:\${${prefix}_PORT}/\${${prefix}_DATABASE}${query}`;
    return [...lines, `clever env set ${variable.name} "${uri}"`];
  }
  const valueName = `${prefix}_VALUE`;
  const lines = [`${valueName}="$(addon_var ${addonName} ${variable.addonVariable})"`];
  if (variable.driverScheme != null) {
    lines.push(`clever env set ${variable.name} "${variable.driverScheme}://\${${valueName}#*://}${query}"`);
  } else if (query !== '' && variable.addonVariable != null && /_URI$|_URL$/.test(variable.addonVariable)) {
    lines.push(`clever env set ${variable.name} "\${${valueName}}${query}"`);
  } else {
    lines.push(`clever env set ${variable.name} "$${valueName}"`);
  }
  return lines;
}

/**
 * @param {string} value
 * @returns {string}
 */
function escapeDoubleQuoted(value) {
  return value.replace(/[\\"$`]/g, (character) => `\\${character}`);
}

const DATA_ENGINES = {
  'mysql-addon': { label: 'MySQL', defaultPort: '3306', defaultUser: 'root', image: 'mysql:8.4' },
  'postgresql-addon': { label: 'PostgreSQL', defaultPort: '5432', defaultUser: 'postgres', image: 'postgres:17' },
  'mongodb-addon': { label: 'MongoDB', defaultPort: '27017', defaultUser: '', image: 'mongo:7' },
};

/**
 * Where the local data lives, from the most to the least reliable source
 * @param {ProjectScanner} scanner
 * @param {MigrationReport} report
 * @param {string} provider
 * @returns {{ composeService: string|null, host: string, port: string, database: string, user: string }}
 */
function findLocalDatabase(scanner, report, provider) {
  const engine = DATA_ENGINES[/** @type {keyof typeof DATA_ENGINES} */ (provider)];
  const addon = report.addons.find((candidate) => candidate.provider === provider);
  const local = {
    composeService: addon?.fromService ?? null,
    host: '127.0.0.1',
    port: engine.defaultPort,
    database: '',
    user: engine.defaultUser,
  };

  for (const variable of report.rewired.filter((candidate) => candidate.addonName === addon?.name)) {
    const uri = /^[a-z][a-z0-9+.-]*:\/\/(?:([^:@/]*)(?::[^@/]*)?@)?([^:/?]+)(?::(\d+))?\/([^?]*)/i.exec(variable.value);
    if (uri != null) {
      Object.assign(local, {
        user: uri[1] || local.user,
        host: uri[2],
        port: uri[3] ?? local.port,
        database: decodeURIComponent(uri[4]) || local.database,
      });
      continue;
    }
    const role =
      Object.entries(variable.uriParts ?? {}).find(([, name]) => name === variable.addonVariable)?.[0] ??
      (variable.addonVariable != null
        ? Object.entries(getRoles(provider)).find(([, name]) => name === variable.addonVariable)?.[0]
        : null);
    if (role === 'host' || role === 'port' || role === 'database' || role === 'user') {
      if (variable.value !== '') {
        local[role] = variable.value;
      }
    }
  }
  // Code already reading the add-on variables keeps the local values as fallback: getenv('MYSQL_ADDON_DB') ?: 'shop'
  const roles = getRoles(provider);
  const fallbackPattern =
    /(?:getenv\(|process\.env\.|os\.getenv\(|os\.environ\.get\()\s*['"]?([A-Z]+_ADDON_[A-Z]+)['"]?\s*\)?\s*(?:\?:|\|\||\?\?|,)\s*['"]([^'"]*)['"]/;
  for (const result of scanner.grep(fallbackPattern)) {
    const role = Object.entries(roles).find(([, name]) => name === result.match[1])?.[0];
    if (role != null && result.match[2] !== '') {
      local[/** @type {'host'|'port'|'database'|'user'} */ (role)] = result.match[2];
    }
  }
  for (const connection of findHardcodedPhpConnections(scanner).filter(
    (candidate) => candidate.engine.provider === provider,
  )) {
    for (const setting of connection.settings) {
      if (setting.role !== 'password' && setting.value !== '') {
        local[/** @type {'host'|'port'|'database'|'user'} */ (setting.role)] = setting.value;
      }
    }
  }
  // Tools connect through a socket for "localhost", and Docker clients cannot reach it
  if (isLocalHost(local.host) || !local.host.includes('.')) {
    local.host = '127.0.0.1';
  }
  return local;
}

/**
 * @param {string} provider
 * @returns {Record<string, string>}
 */
function getRoles(provider) {
  return (
    {
      'mysql-addon': {
        host: 'MYSQL_ADDON_HOST',
        port: 'MYSQL_ADDON_PORT',
        database: 'MYSQL_ADDON_DB',
        user: 'MYSQL_ADDON_USER',
      },
      'postgresql-addon': {
        host: 'POSTGRESQL_ADDON_HOST',
        port: 'POSTGRESQL_ADDON_PORT',
        database: 'POSTGRESQL_ADDON_DB',
        user: 'POSTGRESQL_ADDON_USER',
      },
      'mongodb-addon': {
        host: 'MONGODB_ADDON_HOST',
        port: 'MONGODB_ADDON_PORT',
        database: 'MONGODB_ADDON_DB',
        user: 'MONGODB_ADDON_USER',
      },
    }[provider] ?? {}
  );
}

/**
 * Script copying each local database into its add-on, without storing any password
 * @param {ProjectScanner} scanner
 * @param {MigrationReport} report
 * @returns {string|null}
 */
function buildDataScript(scanner, report) {
  const addons = report.addons.filter((addon) => addon.provider in DATA_ENGINES);
  if (addons.length === 0) {
    return null;
  }
  const lines = [
    '#!/usr/bin/env bash',
    `# ${GENERATED_MARKER}.`,
    '# Copies the local databases into the Clever Cloud add-ons. Run it after clever-setup.sh.',
    '# Local settings can be overridden with the LOCAL_* variables below; passwords are asked, never stored.',
    '# Database clients are used when installed, through Docker otherwise.',
    'set -euo pipefail',
    'cd "$(dirname "$0")"',
    '',
    ...ADDON_VAR_FUNCTION,
    '',
    '# Run a database client installed locally, or through Docker: client <tool> <image> <args...>',
    'client() {',
    '  local tool="$1" image="$2"',
    '  shift 2',
    '  if command -v "$tool" >/dev/null 2>&1; then',
    '    "$tool" "$@"',
    '  else',
    '    docker run --rm -i --network host -e MYSQL_PWD -e PGPASSWORD "$image" "$tool" "$@"',
    '  fi',
    '}',
    '',
    'confirm() {',
    '  local answer',
    '  read -r -p "$1 [y/N] " answer',
    '  [ "$answer" = y ] || [ "$answer" = Y ]',
    '}',
    '',
    'DUMP_DIR="$(mktemp -d)"',
    'trap \'rm -rf "$DUMP_DIR"\' EXIT',
    '',
  ];

  for (const addon of addons) {
    const engine = DATA_ENGINES[/** @type {keyof typeof DATA_ENGINES} */ (addon.provider)];
    const local = findLocalDatabase(scanner, report, addon.provider);
    const key = engine.label.toUpperCase();
    const name = shellQuote(addon.name);
    const dump = `"$DUMP_DIR/${addon.provider}.dump"`;
    const schemaFile = addon.provider === 'mongodb-addon' ? null : findSchemaFile(scanner);
    lines.push(`echo "→ ${engine.label} → add-on ${addon.name}"`);
    const dumpStart = lines.length;

    if (local.composeService != null) {
      lines.push(
        `# The local database runs in the "${local.composeService}" docker-compose service: start it with \`docker compose up -d ${local.composeService}\``,
      );
      const service = shellQuote(local.composeService);
      if (addon.provider === 'mysql-addon') {
        lines.push(
          `docker compose exec -T ${service} sh -c 'exec mysqldump --single-transaction --routines --no-tablespaces -u root -p"$MYSQL_ROOT_PASSWORD" "$MYSQL_DATABASE"' > ${dump}`,
        );
      } else if (addon.provider === 'postgresql-addon') {
        lines.push(
          `docker compose exec -T ${service} sh -c 'exec pg_dump --no-owner --no-acl -U "\${POSTGRES_USER:-postgres}" "\${POSTGRES_DB:-\${POSTGRES_USER:-postgres}}"' > ${dump}`,
        );
      } else {
        lines.push(`docker compose exec -T ${service} mongodump --archive > ${dump}`);
      }
    } else {
      lines.push(
        `LOCAL_${key}_HOST="\${LOCAL_${key}_HOST:-${local.host}}"`,
        `LOCAL_${key}_PORT="\${LOCAL_${key}_PORT:-${local.port}}"`,
        `LOCAL_${key}_DB="\${LOCAL_${key}_DB:-${local.database || report.appName}}"`,
        `LOCAL_${key}_USER="\${LOCAL_${key}_USER:-${local.user}}"`,
      );
      if (addon.provider === 'mysql-addon') {
        lines.push(
          `read -r -s -p "Password of $LOCAL_${key}_USER on the local MySQL (empty if none): " MYSQL_PWD; echo`,
          'export MYSQL_PWD',
          `client mysqldump ${engine.image} --single-transaction --routines --no-tablespaces -h "$LOCAL_${key}_HOST" -P "$LOCAL_${key}_PORT" -u "$LOCAL_${key}_USER" "$LOCAL_${key}_DB" > ${dump}`,
          'unset MYSQL_PWD',
        );
      } else if (addon.provider === 'postgresql-addon') {
        lines.push(
          `read -r -s -p "Password of $LOCAL_${key}_USER on the local PostgreSQL (empty if none): " PGPASSWORD; echo`,
          'export PGPASSWORD',
          `client pg_dump ${engine.image} --no-owner --no-acl -h "$LOCAL_${key}_HOST" -p "$LOCAL_${key}_PORT" -U "$LOCAL_${key}_USER" "$LOCAL_${key}_DB" > ${dump}`,
          'unset PGPASSWORD',
        );
      } else {
        lines.push(
          `LOCAL_${key}_URI="\${LOCAL_${key}_URI:-mongodb://$LOCAL_${key}_HOST:$LOCAL_${key}_PORT/$LOCAL_${key}_DB}"`,
          `client mongodump ${engine.image} --uri "$LOCAL_${key}_URI" --archive > ${dump}`,
        );
      }
    }

    // A SQL file of the project (schema, dump) is an alternative to the local database, which may not exist anymore
    if (schemaFile != null) {
      const dumpLines = lines.splice(dumpStart).map((line) => `  ${line}`);
      const sourceVariable = `${key}_SOURCE`;
      lines.push(
        `SCHEMA_FILE=${shellQuote(schemaFile)}`,
        `${sourceVariable}="\${${sourceVariable}:-}"`,
        `if [ -z "$${sourceVariable}" ]; then`,
        `  read -r -p "Import $SCHEMA_FILE (file) or copy the local database (local)? [file] " ${sourceVariable}`,
        'fi',
        `if [ "\${${sourceVariable}:-file}" = local ]; then`,
        ...dumpLines,
        'else',
        `  cp "$SCHEMA_FILE" ${dump}`,
        'fi',
      );
    }

    lines.push(
      `echo "  SQL to import: $(du -h ${dump} | cut -f1)"`,
      `if confirm "Import it into the ${addon.name} add-on? Existing tables with the same names are replaced"; then`,
    );
    // Read every add-on variable first: a failure inside a command argument would not stop the script
    if (addon.provider === 'mysql-addon') {
      lines.push(
        `  ADDON_HOST="$(addon_var ${name} MYSQL_ADDON_HOST)"`,
        `  ADDON_PORT="$(addon_var ${name} MYSQL_ADDON_PORT)"`,
        `  ADDON_USER="$(addon_var ${name} MYSQL_ADDON_USER)"`,
        `  ADDON_DB="$(addon_var ${name} MYSQL_ADDON_DB)"`,
        `  MYSQL_PWD="$(addon_var ${name} MYSQL_ADDON_PASSWORD)"`,
        '  export MYSQL_PWD',
        `  client mysql ${engine.image} -h "$ADDON_HOST" -P "$ADDON_PORT" -u "$ADDON_USER" "$ADDON_DB" < ${dump}`,
        '  unset MYSQL_PWD',
      );
    } else if (addon.provider === 'postgresql-addon') {
      lines.push(
        `  ADDON_URI="$(addon_var ${name} POSTGRESQL_ADDON_URI)"`,
        `  client psql ${engine.image} "$ADDON_URI" -v ON_ERROR_STOP=1 --quiet < ${dump}`,
      );
    } else {
      const localDatabase = local.composeService != null ? '*' : `$LOCAL_${key}_DB`;
      lines.push(
        `  ADDON_URI="$(addon_var ${name} MONGODB_ADDON_URI)"`,
        `  ADDON_DB="$(addon_var ${name} MONGODB_ADDON_DB)"`,
        `  client mongorestore ${engine.image} --uri "$ADDON_URI" --archive --nsFrom "${localDatabase}.*" --nsTo "$ADDON_DB.*" < ${dump}`,
      );
    }
    lines.push(`  echo "  imported into ${addon.name}"`, 'else', '  echo "  skipped"', 'fi', '');
  }

  lines.push('echo "Done. Restart the application to use the data: clever restart"', '');
  return lines.join('\n');
}

/** Bash functions telling whether the application is linked and whether an add-on exists */
const EXISTENCE_FUNCTIONS = [
  'app_linked() {',
  `  [ -f .clever.json ] && node -e 'const config = JSON.parse(require("fs").readFileSync(".clever.json", "utf8")); process.exit((config.apps ?? []).some((app) => app.alias === process.argv[1]) ? 0 : 1)' "$1"`,
  '}',
  'addon_exists() {',
  `  clever addon list --format json | node -e 'const addons = JSON.parse(require("fs").readFileSync(0, "utf8")); process.exit(addons.some((addon) => addon.name === process.argv[1]) ? 0 : 1)' "$1"`,
  '}',
];

/** SQL files usually holding the schema (and maybe data) of a project, most specific first */
const SCHEMA_FILES = [
  'schema.sql',
  'database.sql',
  'db.sql',
  'structure.sql',
  'dump.sql',
  'init.sql',
  'database/schema.sql',
  'db/schema.sql',
  'sql/schema.sql',
  'sql/init.sql',
  'docker/init.sql',
  'docker/mysql/init.sql',
  'docker/postgres/init.sql',
];

/**
 * @param {ProjectScanner} scanner
 * @returns {string|null}
 */
export function findSchemaFile(scanner) {
  return scanner.first(SCHEMA_FILES) ?? scanner.find(/^[^/]+\.sql$/)[0] ?? null;
}
